- name: Create Organisations.
  uri:
    url: "{{ grafana_api_url }}/api/orgs"
    method: POST
    user: "{{ grafana_config_security.admin_user }}"
    password: "{{ grafana_config_security.admin_password }}"
    body: '{ "name":"{{ organisation.name }}"}'
    force_basic_auth: yes
    body_format: json
  register: grafana_organisation_response

- name: Switch Context to new Organisation
  uri:
    url: "{{ grafana_api_url }}/api/user/using/{{ grafana_organisation_response.json.orgId }}"
    method: POST
    user: "{{ grafana_config_security.admin_user }}"
    password: "{{ grafana_config_security.admin_password }}"
    force_basic_auth: yes

- name: Create Datasource.
  uri:
    url: "{{ grafana_api_url }}/api/datasources"
    method: POST
    user: "{{ grafana_config_security.admin_user }}"
    password: "{{ grafana_config_security.admin_password }}"
    body: '{{ lookup("file", item) }}'
    force_basic_auth: yes
    body_format: json
  with_fileglob: "datasources/*"

- name: Create Dashboards.
  include: create-dashboards.yml
  with_fileglob: "dashboards/*"
  loop_control:
    loop_var: dashboard
