version: '3'

services:
  test-ubuntu-server:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
      - "2222:22"
    environment:
      - PUBLIC_KEY=${PUBLIC_KEY}
    volumes:
      - ${PROJECT_DIR}/scripts/importPublicKey.sh:/root/importKey.sh
    command:
      - /root/importKey.sh
